### ISSUE TITLE
Setup CI (travis)

### ISSUE THREAD

**Issue by eric239** [Glassdoor/planout4j#12]

**Comment by rickhull** [comment]
Working on this now...

**Comment by rickhull** [comment]
Functionality addressed with https://github.com/Glassdoor/planout4j/pull/15

**Comment by rickhull** [comment]
README.md badge addressed with https://github.com/Glassdoor/planout4j/pull/16

**Comment by rickhull** [comment]
Closing this issue, though we could take this further by testing across different JDKs and versions, maybe other test-matrixy stuff.
