### ISSUE TITLE
Provide extensible logging functionality

### ISSUE THREAD

**Issue by reikje** [Glassdoor/planout4j#27]
Not sure this doesn't exist yet but is there a way to easily log experiments like in the Python implementation? https://facebook.github.io/planout/docs/extending-logging.html

**Comment by eric239** [comment]
Hi @reikje, there's issue #23 already out there. We don't have logging like in the original PO yet primarily due to lack of clear consensus on where/how to log to. If you have specific ideas, comments, and/or would like to contribute please comment in #23

**Comment by reikje** [comment]
Okay will leave some comments with #23 later on. Need to start using planout4j first :) Where is it best to ask some questions?

**Comment by eric239** [comment]
Good question :smile: We will set up a discussion forum. In the meanwhile, feel free to reach out to me directly ernest [at] alerweb [dot] com

**Comment by eric239** [comment]
Closing this one, let's have logging conversation in the GG or in #23
