### ISSUE TITLE
Not able to package the project

### ISSUE THREAD

**Issue by grvshaha** [Glassdoor/planout4j#34]
Test cases for dsl compiler are failing at my end. 

Results :

Failed tests:   test_dsl_to_json(com.glassdoor.planout4j.compiler.PlanoutDSLCompilerTest): expected: com.google.common.collect.RegularImmutableMap<{op=set, var=x, value=2.0}> but was: java.util.LinkedHashMap<{op=set, var=x, value=2.0}>

Tests run: 4, Failures: 1, Errors: 0, Skipped: 0

**Comment by eric239** [comment]
@grvshaha are you using latest 1.1 code? I can't reproduce this, and travis build is green.

**Comment by grvshaha** [comment]
Yup. I am using latest 1.1 code. 

Sending you the steps. Let me know if I am doing anything wrong here : 
1) Cloning the release branch 
git clone -b RELEASE-1.1 https://github.com/Glassdoor/planout4j.git

2) Going into planout4j directory. 
cd planout4j

3) trying to package with the help of maven
mvn clean package

mvn version : 3.3.3
java version : 1.7

**Comment by eric239** [comment]
Sorry, not reproducible

**Comment by grvshaha** [comment]
Thanks for your help. Issue is resolved now.

**Comment by grvshaha** [comment]
Looks like its OS - Java version compatibility issue. 

Maven install is working in Ubuntu 12.04 - Java 7 and Ubuntu 15.04 - Java 8 combination, but it is not working in Ubuntu 15.04 and Java 7.
