### ISSUE TITLE
planout shipping tool -- multiple (buggy) json implementations

### ISSUE THREAD

**Issue by rickhull** [Glassdoor/planout4j#35]
Hi @eric239! 

Vance and I finally tracked down a ship tool bug.  It appears to manifest on Linux using OpenJDK 1.7.  We think that it does not manifest against OracleJDK.

The issue is that invalid JSON ends up shipped to Redis.  We tried to reproduce first without redis by using the `compile` command.  However, the output of `compile` is valid.  We dug deeper and discovered that `compile` generates the final JSON output using a different library than than `ship`.

`compile` [uses Gson](https://github.com/Glassdoor/planout4j/blob/master/tools/src/main/java/com/glassdoor/planout4j/tools/CompileTool.java#L52-L54) to generate the final JSON ouput

`ship` [uses simple.json.org JSONValue](https://github.com/Glassdoor/planout4j/blob/ea927147f411956d2f8897d08cab71ac0f5bc5f9/config/src/main/java/com/glassdoor/planout4j/config/Planout4jConfigShipperImpl.java#L46) to generate the final JSON output

So it looks the invalid JSON is generated with the combination of JSONValue, Linux, and OpenJDK 1.7.  Gson output looks good by comparison.

Is there any reason to use the two different libraries?  Gson looks (naively) a bit tougher to use because it wants an additional `parsedArgs`parameter to ultimately be passed its way.

**Comment by thorntonv** [comment]
It looks like the issue arises from a difference in the Oracle/OpenJDK JavaScript engines. In the OpenJDK engine some strings are ConsString instances rather than standard java Strings.

**Comment by eric239** [comment]
Happy to **finally** see this Sherlock-style mystery finally nailed down!
Another p4j user reported that the combo of Linux + OpenJDK was the culprit in #34 but you guys dug to the root.

I'll be happy to fix (get rid of simple json) and release 1.2 over the weekend; if you want it sooner or want to handle yourselves go ahead, just keep me in the loop via PR.

**Comment by rickhull** [comment]
:cake:

I think Vance has a PR in mind -- but I'm also wondering if we're doing the "same thing" via different methodologies in other places.  For instance, I assumed that, by design, the `ship` portion would rely on or call into the `compile` portion.  Instead, it looks like they were implemented in completely different silos.

Maybe an opportunity to revisit the design a little bit?

**Comment by eric239** [comment]
There some legacy (dos) artifacts... compile was built by me, whereas ship was built by Phanindra.

I won't endeavor on a refactoring campaign b/c I'm swamped elsewhere, but can help with an advice here and there if you guys decide to.

**Comment by eric239** [comment]
Closing as the primary issue was addressed, other comments can be pulled into separate threads as needed
