### ISSUE TITLE
Low performance for getting param

### ISSUE THREAD

**Issue by dangchienhsgs** [Glassdoor/planout4j#41]
Dear Glassdoor team,

I test a simple experiment like this

```namespace:
  unit: userid
  segments: 100

experiment_definitions:
  - definition: Default_Experiment
    assign: !planout |
      button_color = '#000000';
      button_text  = 'Register';
  - definition: Button_Experiment
    assign: !planout |
      button_color = uniformChoice(choices=['#ff0000', '#00ff00'], unit=userid);
      button_text  = weightedChoice(choices=['Join now!', 'Sign up.'], weights=[0.7, 0.3], unit=userid);

default_experiment: Default_Experiment

experiment_sequence:
  - action: add
    definition: Button_Experiment
    name: Button_Experiment.1
    segments: 100
```

With my computer (Core I5, 8GB Ram), I benchmark planout by this test and receive the low result (about 6000 random operators / s). How could I can scale it up to about 100000 op/s ?

**Comment by eytan** [comment]
I am not familiar with the details of how hashing for namespaces work for PlanOut4J, but the function used to map users to segments when mapping userids to experiments in a namespace is not optimized in the PlanOut reference implementation.  In most production settings I would recommend allocating segments to experiments in a one-time fashion, and storing this mapping in a database.  However, if you do not wish to use a database, I might suggest porting the performance improvements Guy Aridor recently made to PlanOut.js and the reference implementation, which has a much much faster sample operator which will substantially speed up the hashing from users to experiments:
  https://github.com/HubSpot/PlanOut.js/pull/21
  https://github.com/HubSpot/PlanOut.js/pull/22

**Comment by eric239** [comment]
@dangchienhsgs we have performance test in place. Please get the source code, and 
```
cd api && mvn clean test -Dtest=ConcurrentAccessTest
```
then please share the output.

@eytan the p4j code is actually fairly well-performant (as we have observed running the aforementioned test ourselves, as well as in production settings) although the performance has never been the top priority.

**Comment by eytan** [comment]
@eric239 all PlanOut implementations would benefit from Guy's performance improvements -- it's an order of magnitude faster and trivial to implement, so it might be something to consider regardless...

**Comment by eric239** [comment]
Thanks Eytan, noted. I'll open another issue to track that as an enhancement.
