### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by nkconnor** [Glassdoor/planout4j#53]
Master branch contains multiple changes, including logging, which should be distributed on Maven

**Comment by eric239** [comment]
@nkconnor this project is in need of a new maintainer -- I'm working a very demanding full time job in a company that doesn't use planout4j any longer and cannot continue to perform maintenance duties.

**Comment by nkconnor** [comment]
Understood. I'll probably be making improvements to the codebase over the next few weeks - wonder if best to just maintain a fork?

**Comment by rickhull** [comment]
@nkconnor I think a fork would be appropriate.  I worked with @eric239 at Glassdoor, and on this codebase in a very small way.  I don't believe Glassdoor has any intention of maintaining it.

**Comment by eric239** [comment]
I agree with @rickhull -- perhaps @nkconnor you can pick up others' PRs as well and give this code new life in your fork.

**Comment by nkconnor** [comment]
That sounds good with me. We're building a Scala API on top of the code base and will be happy to maintain and improve both for the foreseeable future.

The fork is currently @ https://github.com/nkconnor/planout4j

**Comment by eric239** [comment]
Glad there's still some interest, @nkconnor -- it was a fun project to work on.
I've modified README and posted to GG pointing to your fork.
Good luck!

**Comment by tokuhirom** [comment]
@nkconnor If you are a new active maintainer, could you release a new version to the maven central?

**Comment by nkconnor** [comment]
@tokuhirom I'm in the process of building and releasing the project. I'll post an update to https://github.com/nkconnor/planout4j whenever they are out
